### ISSUE TITLE
Crashes during installation, "SyntaxError: Invalid file magic number"

### ISSUE THREAD

**Issue by accidentalcoincidence** [ralgar/proton-mo2-installer#10]
I am trying to install MO2 for Skyrim SE, resulting in a popup saying "Installation failed". this is what shows up in the console, it looks like what's immediately raising the error is actually protontricks:
(rerunning the installer gives me the option to update MO2, which fails in the same way)

```Traceback (most recent call last):
  File "/usr/bin/protontricks", line 33, in <module>
    sys.exit(load_entry_point('protontricks==1.7.0', 'console_scripts', 'protontricks')())
  File "/usr/lib/python3/dist-packages/protontricks/cli/main.py", line 28, in cli
    main(args)
  File "/usr/lib/python3/dist-packages/protontricks/cli/util.py", line 143, in wrapper
    return cli_func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/protontricks/cli/main.py", line 264, in main
    proton_app = find_proton_app(
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 624, in find_proton_app
    tool_app = find_steam_compat_tool_app(
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 537, in find_steam_compat_tool_app
    tool_appid = get_tool_appid(compat_tool_name, appinfo_path)
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 418, in get_tool_appid
    vdf_sections = get_appinfo_sections(appinfo_path)
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 385, in get_appinfo_sections
    raise SyntaxError("Invalid file magic number")
SyntaxError: Invalid file magic number```

**Comment by ralgar** [comment]
Hmm, not sure exactly what's going on there, but you're right it is Protontricks throwing the error. I'm pretty sure the prefix hacks aren't necessary with newer versions of Proton anyway, so let's try disabling them.

Please edit the file `gamesinfo/skyrimspecialedition.sh`, and remove the verb from the protontricks array:

```sh
# From this
game_protontricks=("xaudio2_7=native")

# To this
game_protontricks=()
```

Then run Install or Update again. Let me know if that works, and if there are any in-game sound issues, and I'll update the repo accordingly.

**Comment by accidentalcoincidence** [comment]
this appears to have worked, mod organizer is installed and loads mods, no audio issues so far

**Comment by ralgar** [comment]
Thanks for confirming that everything works well. If there were any audio issues, they would be immediately apparent with NPC dialog.

I've gone ahead and removed that outdated `xaudio2_7` verb from Fallout 4, Skyrim SE, and Enderal SE. Installation for these games will no longer call `protontricks`, as there are no verbs to install.
