### ISSUE TITLE
The method you use to find libraryfolders.vdf is really slow and probably unnecessary

### ISSUE THREAD

**Issue by erisdev** [ralgar/proton-mo2-installer#12]
The file should reasonably be at `$XDG_DATA_HOME/Steam/config/libraryfolders.vdf` for a normal steam install. If you look there first and only use the find command as a fallback in 99% of cases you'll find it right away. The find command took about 10 minutes to finish on my system because my home directory is huge and lives on an actual HDD.

**Comment by ralgar** [comment]
Yeah, I think this was something I originally did to handle a couple of weird edge cases that I discovered, but it's definitely unnecessary for the vast majority of installations. I've implemented your suggestion on the main branch, keeping the find command as a fallback. Discovery should be immediate now. Thanks for the suggestion.
