### ISSUE TITLE
Setting nxm handler fails because nxm-broker.sh is not in PATH yet

### ISSUE THREAD

**Issue by erisdev** [ralgar/proton-mo2-installer#13]
The command `xdg-mime default nxm-handler.desktop x-scheme-handler/nxm` fails if the command `nxm-broker.sh` is not found in PATH. Since the installer runs this command before installing the script, it always fails unless the script was previously installed.

**Comment by ralgar** [comment]
This isn't an issue that I'm able to reproduce on my system, but I've gone ahead and moved the command invocation to after the script is installed. Does that resolve the issue for you?

**Comment by erisdev** [comment]
Yes, thank you.

I couldn't say for sure, but this might be a recent-ish change in glib(?) that'd be coming down the pipe for other folks eventually. I'm using an arch fork so packages are typically pretty up to date and sometimes we get to see stuff break first.

**Comment by ralgar** [comment]
I'm actually running Arch myself, and still couldn't repro. Very strange. Anyway, I'm glad it's resolved for you now.

Edit: Never mind, I had gone a couple of days without updates, and I see those new packages just dropped.
