### ISSUE TITLE
RC8 Simple Band-Aid Fix for Ubuntu

### ISSUE THREAD

**Issue by cprin21** [ralgar/proton-mo2-installer#4]
Changing ```python``` to ```python3``` in line 1 (the hashbang) of /utils/compat-tool-remap.py makes the install script work on Ubuntu.
I have not tested other APT based distros but I'm assuming this works
![Screenshot from 2022-06-23 18-01-29](https://user-images.githubusercontent.com/107228497/175422639-98aa2501-8a6e-4a2d-8df5-04858d1e65db.png)
.

**Comment by ralgar** [comment]
You're correct, it should be `python3`. Thanks for the heads up, I'll push a fix when I get a second.

**Comment by ralgar** [comment]
Fixed this and released v1.0.0 stable. Thanks again.
