### ISSUE TITLE
Fallout New Vegas xNVSE Out of Date

### ISSUE THREAD

**Issue by cprin21** [ralgar/proton-mo2-installer#6]
A lesser degree of an issue but MO2's built-in LOOT reports that xNVSE is out of date, this is due to a new xNVSE version releasing after 1.0.0's release. Not expecting to get an update everytime a script extender gets a new version but thought it was something to note regardless.

**Comment by ralgar** [comment]
Thanks for the issue, I'm surprised NVSE is still updated. I'll bump the script extender version at the same time I deal with #5.

If you want to fix this for yourself, you can update the script extender URL in `gamesinfo/falloutnewvegas.sh`

**Comment by ralgar** [comment]
This is now updated with [v1.0.1](https://github.com/ralgar/proton-mo2-installer/releases/tag/v1.0.1).
